app <- ShinyDriver$new("../../")
app$snapshotInit("mytest")

app$setInputs(grouping_factor = "Penicillin resistance")
app$snapshot()
app$setInputs(grouping_factor = "Macrolide resistance")
app$snapshot()
app$setInputs(grouping_factor = "Type")
app$snapshot()
app$setInputs(y = "Absolute count")
app$snapshot()
app$setInputs(grouping_factor = "Penicillin resistance")
app$snapshot()
app$setInputs(grouping_factor = "Macrolide resistance")
app$snapshot()
